---
- hosts: all
  pre_tasks:
  - name: Update apt cache if needed.
    apt:
      update_cache=yes
      cache_valid_time=3600

- name: Web server
  hosts: web
  roles:
   - apache
- name: DB server
  hosts: db
  roles:
   - mysql
