---
# WordPress configuration
- name: Install WP-CLI
  get_url:
    url: "https://raw.github.com/wp-cli/builds/gh-pages/phar/wp-cli.phar"
    dest: "/usr/bin/wp"
    force: true
    owner: root
    group: root
    mode: 0755
  tags: [ wordpress ]
  
- name: Make finish installation
  shell: 'sudo -u www-data /usr/bin/wp --path=/var/www/wordpress/ core install --url="http://{{ http_host }}/" --title="{{ wp_title }}" --admin_name={{ wp_admin }} --admin_password={{ wp_admin_password }} --admin_email={{ wp_admin_email }}'
  tags: [ wordpress ]

- name: Install and activate LDAP Plugin
  shell: 'sudo -u www-data /usr/bin/wp --path=/var/www/wordpress/ plugin install https://downloads.wordpress.org/plugin/authldap.zip --activate'
  args:
    creates: /var/www/wordpress/wp-content/plugins/authldap
  tags: [ wordpress ]
  
- name: Set LDAP config
  vars:
    authldap: "{{ lookup('template', 'files/wp-ldap.j2') | from_yaml}}"
  shell: "sudo -u www-data /usr/bin/wp --path=/var/www/wordpress/ option update authLDAPOptions --format=json '{{ authldap | to_json}}'"
  tags: [ wordpress ]
