---
# WordPress installation
- name: Download and unpack latest WordPress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: "/var/www/"
    remote_src: yes
    creates: "/var/www/wordpress/wp-config.php"
  tags: [ wordpress ]

- name: Set ownership
  file:
    path: "/var/www/wordpress"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
  tags: [ wordpress ]

- name: Set permissions for directories
  shell: "/usr/bin/find /var/www/wordpress/ -type d -exec chmod 750 {} \\;"
  tags: [ wordpress ]

- name: Set permissions for files
  shell: "/usr/bin/find /var/www/wordpress/ -type f -exec chmod 640 {} \\;"
  tags: [ wordpress ]

- name: Set up wp-config
  template:
    src: "files/wp-config.php.j2"
    dest: "/var/www/wordpress/wp-config.php"
  tags: [ wordpress ]
