---
## installs and sets up MySQL
- name: Install MySQL Package
  apt: name={{ item }} state=latest
  loop: [ 'mysql-server', 'python3-pymysql' ]
  tags: [ mysql ]
  
- name: Start MySQL Service
  service: name=mysql state=started enabled=yes
  tags: [ mysql ]
      
- name: Set the root password
  mysql_user:
    check_implicit_admin: yes # Try root/no_password first
    name: root
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true
  tags: [ mysql, mysql-root ]

- name: Remove all anonymous user accounts
  mysql_user:
    name: ''
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true
  tags: [ mysql ]

- name: Remove the MySQL test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  tags: [ mysql ]

- name: Creates database for WordPress
  mysql_db:
    name: "{{ mysql_db }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  tags: [ mysql ]

- name: Create MySQL user for WordPress
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_db }}.*:ALL"
    host: "{{ mysql_client_host }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true
  tags: [ mysql ]
  
- name: Set up mysqld.cnf
  template:
    src: "files/mysqld.cnf.j2"
    dest: "/etc/mysql/mysql.conf.d/mysqld.cnf"
    owner: root
    mode: 0644
  tags: [ mysql ]

- name: Start MySQL Service
  service: name=mysql state=restarted
  tags: [ mysql ]
